# Generated by Django 5.0.3 on 2024-03-31 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'verbose_name': 'Подгруппа', 'verbose_name_plural': 'Подгруппы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['fio'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterField(
            model_name='class',
            name='digit',
            field=models.IntegerField(verbose_name='Цифра'),
        ),
        migrations.AlterField(
            model_name='class',
            name='letter',
            field=models.CharField(max_length=1, verbose_name='Буква'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='program',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='program',
            name='discipline_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='program',
            name='load',
            field=models.IntegerField(verbose_name='Нагрузка'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='discipline_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='group_number',
            field=models.IntegerField(verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fio',
            field=models.TextField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(null=True, upload_to='teachers/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.IntegerField(verbose_name='Кабинет'),
        ),
    ]
