# Generated by Django 5.0.3 on 2024-05-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='class_id',
            new_name='cls',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='discipline_id',
            new_name='discipline',
        ),
    ]
