# Generated by Django 5.0.3 on 2024-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_class_options_alter_discipline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, to='teachers.discipline'),
        ),
    ]
