# Generated by Django 5.0.3 on 2024-05-22 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('subject', models.ManyToManyField(blank=True, to='teachers.discipline', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Параллель',
                'verbose_name_plural': 'Параллели',
            },
        ),
        migrations.CreateModel(
            name='GradeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField(blank=True, null=True, verbose_name='Нагрузка')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.discipline', verbose_name='Дисциплина')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.grade', verbose_name='Параллель')),
            ],
            options={
                'verbose_name': 'Программа параллели',
                'verbose_name_plural': 'Программы параллелей',
            },
        ),
    ]
