# Generated by Django 5.0.3 on 2024-05-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_grade_gradeprogram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeprogram',
            old_name='discipline',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
    ]
