# Generated by Django 5.0.3 on 2024-04-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(blank=True, to='teachers.discipline', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.PositiveIntegerField(verbose_name='Кабинет'),
        ),
    ]
