# Generated by Django 5.0.3 on 2024-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_class_options_alter_class_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['name'], 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='short_name',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Краткое название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кабинет'),
        ),
    ]
