# Generated by Django 5.0.3 on 2024-04-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_teachersubjectclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersubjectclass',
            old_name='class_id',
            new_name='_class',
        ),
        migrations.RenameField(
            model_name='teachersubjectclass',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='teachersubjectclass',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
