# Generated by Django 5.0.3 on 2024-04-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_rename_class_id_teachersubjectclass__class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='discipline_id',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='teacher_id',
        ),
        migrations.AddIndex(
            model_name='teachersubjectclass',
            index=models.Index(fields=['teacher', '_class', 'subject'], name='unique_teacher_class_subject'),
        ),
        migrations.DeleteModel(
            name='Subgroup',
        ),
    ]
