# Generated by Django 5.0.3 on 2024-04-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_remove_subgroup_class_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teachersubjectclass',
            name='unique_teacher_class_subject',
        ),
        migrations.AddIndex(
            model_name='teachersubjectclass',
            index=models.Index(fields=['_class', 'subject'], name='unique_class_subject'),
        ),
    ]
