# Generated by Django 5.0.3 on 2024-05-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.IntegerField(default=5, verbose_name='Параллель')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Программы',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='ProgramDisciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField(blank=True, null=True, verbose_name='Нагрузка')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.discipline', verbose_name='Дисциплина')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Программа и дисциплины',
                'verbose_name_plural': 'Программы и дисциплины',
            },
        ),
    ]
