# Generated by Django 5.0.3 on 2024-05-30 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['digit', 'name'], 'verbose_name': 'Программы', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AddField(
            model_name='program',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='program',
            name='digit',
            field=models.IntegerField(verbose_name='Параллель'),
        ),
    ]
