# Generated by Django 5.0.3 on 2024-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_class_id_program_cls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='load',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нагрузка'),
        ),
    ]
