# Generated by Django 5.0.3 on 2024-05-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_program_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(blank=True, to='teachers.discipline', verbose_name='Предметы'),
        ),
    ]
