# Generated by Django 5.0.3 on 2024-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, to='teachers.discipline', verbose_name='Предметы'),
        ),
    ]
