# Generated by Django 5.0.3 on 2024-04-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
