# Generated by Django 5.0.3 on 2024-04-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_alter_discipline_options_alter_discipline_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.class', verbose_name='Класс')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.discipline', verbose_name='Дисциплина')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Учитель-Предмет-Класс',
                'verbose_name_plural': 'Учителя-Предметы-Классы',
            },
        ),
    ]
