# Generated by Django 5.0.3 on 2024-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_remove_teachersubjectclass_unique_teacher_class_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(blank=True, through='teachers.Program', to='teachers.discipline', verbose_name='Предметы'),
        ),
    ]
