# Generated by Django 5.0.3 on 2024-05-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Параллель',
                'verbose_name_plural': 'Параллели',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.IntegerField(verbose_name='Цифра')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cls.level', verbose_name='Параллель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['digit', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='LevelProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField(blank=True, null=True, verbose_name='Нагрузка')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.discipline', verbose_name='Дисциплина')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cls.level', verbose_name='Параллель')),
            ],
            options={
                'verbose_name': 'Программа параллели',
                'verbose_name_plural': 'Программы параллелей',
            },
        ),
        migrations.CreateModel(
            name='TeacherDisciplineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cls.class', verbose_name='Класс')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.discipline', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Учитель-Предмет-Класс',
                'verbose_name_plural': 'Учителя-Предметы-Классы',
                'indexes': [models.Index(fields=['cls', 'discipline'], name='unique_class_subject')],
            },
        ),
    ]
