# Generated by Django 5.0.3 on 2024-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='digit',
            field=models.IntegerField(default=5, verbose_name='Параллель'),
        ),
    ]
