# Generated by Django 5.0.3 on 2024-05-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0002_level_digit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelprogram',
            name='level',
        ),
        migrations.RemoveField(
            model_name='class',
            name='level',
        ),
        migrations.RemoveField(
            model_name='levelprogram',
            name='discipline',
        ),
    ]
