# Generated by Django 5.0.3 on 2024-05-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0003_remove_levelprogram_level_remove_class_level_and_more'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='program.program', verbose_name='Параллель'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='LevelProgram',
        ),
    ]
